[package]
name = "cojudge-desktop"
version = "0.0.9"
description = "Cojudge desktop application"
edition = "2021"
license = "MIT"

[build-dependencies]
tauri-build = { version = "=2.6.3", features = [] }

[dependencies]
getrandom = "=0.3.4"
tauri = { version = "=2.11.5", features = [] }
tauri-plugin-opener = "=2.5.4"
